#!/usr/bin/env python3
"""
derive_samplesheet.py
======================
Derives a Cirro-style samplesheet.csv from an existing SPATIA experiment
YAML's `experiment.image_experiment_group_map` + `paths.masked_roi_dir`,
and writes a companion "params" file with the per-sample bits commented
out (not deleted -- diff it against the original to see exactly what
moved and why).

Context: this is step 1 of Dima's (Cirro admin) ask, 2026-09-24 --
split sample metadata (which image belongs to which sample/group) out
of the hand-written experiment YAML into a samplesheet CSV, so a new
dataset only needs a new samplesheet, not a hand-edited copy of the
whole config. Everything else in the YAML (thresholds, which steps run,
marker panel, cell-typing settings, etc.) is left completely untouched
-- those are real pipeline parameters, not sample metadata, and stay in
the config per Q10 (single batched process across all samples,
unchanged -- this script does not change how many times the pipeline
runs, only where the sample list comes from).

Usage:
    python derive_samplesheet.py --config experiments/crc_tma_full_pipeline.yaml \
        --samplesheet-out experiments/samplesheet_crc_tma_full.csv \
        --params-out experiments/crc_tma_full_pipeline.params.yaml

NOT YET WIRED into run_pipeline.py or main.nf -- this only produces the
two files for review. run_pipeline.py still expects one --config YAML
with image_experiment_group_map/masked_roi_dir baked in; teaching it to
read --samplesheet instead is the next step, deliberately not done here
until you've looked at the output and confirmed the split is right.

LIMITATION: the params-file rewrite is a text-level comment-out tuned to
this file's actual indentation (2-space experiment: block, 4-space
group-map entries) -- it is not a general YAML formatter, and won't
necessarily handle a differently-formatted config correctly. Always
check the diff before trusting the .params.yaml output.
"""
import argparse
import csv
import re
import sys
from pathlib import Path

import yaml


def load_sample_rows(config_path: Path):
    with open(config_path) as f:
        cfg = yaml.safe_load(f)

    group_map = (cfg.get("experiment") or {}).get("image_experiment_group_map")
    if not group_map:
        sys.exit(
            f"No experiment.image_experiment_group_map found in {config_path} -- "
            "nothing to derive a samplesheet from. Is this the right config?"
        )

    masked_roi_dir = (cfg.get("paths") or {}).get("masked_roi_dir")
    if not masked_roi_dir:
        sys.exit(f"No paths.masked_roi_dir found in {config_path}.")

    rows = []
    for folder, group in group_map.items():
        image_path = f"{masked_roi_dir.rstrip('/')}/{folder}"
        rows.append({"sample_id": folder, "image_path": image_path, "group": group})
    return rows


def write_samplesheet(rows, out_path: Path):
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with open(out_path, "w", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=["sample_id", "image_path", "group"])
        writer.writeheader()
        writer.writerows(rows)


def write_params_file(config_path: Path, out_path: Path):
    text = config_path.read_text().splitlines(keepends=True)
    out_lines = []
    in_group_map_block = False
    header = (
        "# ============================================================\n"
        "# AUTO-DERIVED params file -- generated by derive_samplesheet.py from\n"
        f"# {config_path.name}. Sample metadata (image_experiment_group_map,\n"
        "# masked_roi_dir/raw_image_dir) is commented out below -- it now lives\n"
        "# in the companion samplesheet CSV. Everything else, including every\n"
        "# original comment, is untouched.\n"
        "# DRAFT -- review before use. Not yet wired into run_pipeline.py.\n"
        "# ============================================================\n"
    )
    out_lines.append(header)

    for line in text:
        stripped = line.rstrip("\n")

        if re.match(r"^\s*image_experiment_group_map:\s*$", stripped):
            in_group_map_block = True
            out_lines.append(
                "  # image_experiment_group_map: -- MOVED to samplesheet CSV (sample_id/group columns)\n"
            )
            continue
        if in_group_map_block:
            if re.match(r"^\s{4,}\S", stripped):
                out_lines.append("  # " + stripped.lstrip() + "\n")
                continue
            if stripped.strip() == "":
                out_lines.append(line)
                continue
            in_group_map_block = False  # falls through to normal handling below

        if re.match(r'^\s*(raw_image_dir|masked_roi_dir):\s*".*"\s*$', stripped):
            out_lines.append(
                f"  # {stripped.strip()}  -- MOVED to samplesheet CSV (image_path column)\n"
            )
            continue

        out_lines.append(line)

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("".join(out_lines))


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--config", required=True, type=Path)
    ap.add_argument("--samplesheet-out", required=True, type=Path)
    ap.add_argument("--params-out", required=True, type=Path)
    args = ap.parse_args()

    rows = load_sample_rows(args.config)
    write_samplesheet(rows, args.samplesheet_out)
    write_params_file(args.config, args.params_out)

    print(f"Wrote {len(rows)} sample rows to {args.samplesheet_out}")
    print(f"Wrote params file (sample metadata commented out) to {args.params_out}")
    for r in rows:
        print(f"  {r['sample_id']:14s} group={r['group']:4s} path={r['image_path']}")


if __name__ == "__main__":
    main()
