/*
===============================================================================
SPATIA Pipeline - Cell-Typing Visualization Script (automatic track)
File: 05-5_celltyping_visualization.groovy
===============================================================================

STATUS
------
Written but NOT executed against a real QuPath project -- this sandbox has
no QuPath installation to run it in. Modeled directly on the same
import/render pattern already used in 07-2_triad_visualization.groovy
(ellipse detections at centroid, PathClass + color per category, TSV
columns attached as measurements/metadata via storeMetadataValue()).
Spot-check the first real run's rendered cell count against the export
step's own printed count (`[celltype_qupath_export] N cells exported...`)
before trusting the QuPath view.

-------------------------------------------------------------------------------

OVERVIEW
--------
Imports the *_celltypes.tsv file produced by
spatia/analysis/cell_typing.py's export_qupath_celltypes() (run_pipeline.py's
cell_typing step, gated by config key cell_typing.qupath_export.enabled) and
renders every typed cell as a colored ellipse detection object at its
centroid, directly in the open QuPath project.

Added 2026-10-02 at Afrouz's request, specifically so Unassigned cells can
be adjudicated by eye: each Unassigned cell is rendered in a fixed neutral
grey (matching cell_typing.py's own plotting convention, see
plot_spatial_celltype_overlay's docstring) and carries two pieces of
QuPath metadata no other export in this repo attaches --
  • positive_markers  -- every marker this specific cell is positive for
  • candidate_pattern -- when this cell's marker signature matches one of
    the top-15 recurring patterns already written to
    cell_typing_data/unassigned_candidate_cell_types.csv, that row's rank
    and placeholder name (blank otherwise)
-- so clicking an Unassigned cell in QuPath shows both its real marker
profile and (where one exists) a candidate-type suggestion, in the tissue
context that generated it, without leaving QuPath to cross-reference a
separate CSV.

Each row (one cell) is rendered:
  • At its centroid location (global pixel coordinates, used directly --
    same coordinate handling as 07-2, no tile-offset math needed: cell
    typing runs on whole-image/whole-core data, not tiles)
  • Colored by cell_type -- a deterministic palette assigned by sorting
    the distinct cell_type values found in THIS file and cycling a fixed
    20-color list, so the same cell_type gets the same color across runs
    of this script on the same TSV (not stable across different TSVs with
    a different cell_type vocabulary -- CRC vs LILRB2 panels do not share
    one hardcoded map, same caveat as spatia/analysis/visualization.py's
    own docstring). "Unassigned" is always pinned to grey, matching that
    module's convention, so it never competes visually with a real call.
  • Named after its cell_id (visible in QuPath's object list and
    searchable)
  • Tagged with cell_type, tissue_id, experiment_group, positive_markers,
    and candidate_pattern as QuPath metadata (string key/value pairs)
  • Tagged with area as a numeric measurement, where the TSV has it

-------------------------------------------------------------------------------

USER CONFIGURATION PARAMETERS
-----------------------------

tsvPath (String)
  -> Full path to the *_celltypes.tsv file generated by
     export_qupath_celltypes() (one per tissue_id/core, under
     {output_dir}/celltype_qupath_exports/)

pointRadius (double)
  -> Radius in pixels for each rendered ellipse, used when the TSV has no
     area column. Default: 5.0 (matches 05-4-2's no-area fallback).

unassignedOnly (boolean)
  -> When true, only renders cells whose cell_type == "Unassigned" --
     useful for a focused adjudication pass without the full typed
     population cluttering the view. Default: false (renders everything).

-------------------------------------------------------------------------------

REQUIRED TSV COLUMNS
---------------------
cell_id, centroid_x, centroid_y, cell_type

OPTIONAL TSV COLUMNS
---------------------
tissue_id, experiment_group, positive_markers, candidate_pattern, area
(any may be blank on a given row)

-------------------------------------------------------------------------------

PREREQUISITES
----------------
• QuPath with Groovy scripting support
• TSV generated from: spatia/analysis/cell_typing.py's
  export_qupath_celltypes(), called automatically by run_cell_typing() when
  cell_typing.qupath_export.enabled: true is set in the pipeline config
  (see experiments/crc_tma_full_pipeline.yaml for the production example)
• Run via: QuPath -> Automate -> Script Editor -> paste -> Run
  (interactive only -- no headless/CLI mode, same limitation as
  00_ROI_extract_mask_project.groovy, 05-4-2, and 07-2)

-------------------------------------------------------------------------------

RELATED SCRIPTS
-------------------
spatia/analysis/cell_typing.py (run_cell_typing / export_qupath_celltypes)
  -> Types cells, writes *_celltypes.tsv

05-5_celltyping_visualization.groovy
  -> This script -> renders typed cells (incl. Unassigned + candidates) in QuPath

07-2_triad_visualization.groovy
  -> Sibling script for the triads export -- same import/render pattern

===============================================================================
*/
import qupath.lib.objects.PathObjects
import qupath.lib.roi.ROIs
import qupath.lib.regions.ImagePlane
import qupath.lib.objects.classes.PathClass

// ============================================================
// ⚠️  USER CONFIGURATION — CHANGE THIS PATH
// ============================================================
def tsvPath        = "/path/to/celltype_qupath_exports/TISSUE_ID_celltypes.tsv"
def pointRadius     = 5.0
def unassignedOnly  = false

// ============================================================
// FIXED COLORS
// ============================================================
def UNASSIGNED_COLOR = getColorRGB(160, 160, 160)   // neutral grey -- never competes with a real call
def PALETTE = [
    getColorRGB(31,  119, 180), getColorRGB(255, 127, 14),  getColorRGB(44,  160, 44),
    getColorRGB(214, 39,  40),  getColorRGB(148, 103, 189), getColorRGB(140, 86,  75),
    getColorRGB(227, 119, 194), getColorRGB(188, 189, 34),  getColorRGB(23,  190, 207),
    getColorRGB(255, 187, 120), getColorRGB(152, 223, 138), getColorRGB(255, 152, 150),
    getColorRGB(197, 176, 213), getColorRGB(196, 156, 148), getColorRGB(247, 182, 210),
    getColorRGB(199, 199, 199), getColorRGB(219, 219, 141), getColorRGB(158, 218, 229),
    getColorRGB(255, 152, 0),   getColorRGB(76,  175, 80),
]

// ============================================================
// READ TSV
// ============================================================
def allLines = new File(tsvPath).readLines()
if (allLines.size() < 2) {
    println "ERROR: TSV file is empty or has no data rows: ${tsvPath}"
    return
}

def headers   = allLines[0].split('\t').toList()
def dataLines = allLines[1..-1]

def requiredCols = ['cell_id', 'centroid_x', 'centroid_y', 'cell_type']
def missingCols = requiredCols.findAll { headers.indexOf(it) < 0 }
if (missingCols) {
    println "ERROR: Missing required columns: ${missingCols}"
    println "Available headers: ${headers}"
    return
}

def cid_idx    = headers.indexOf('cell_id')
def cx_idx     = headers.indexOf('centroid_x')
def cy_idx     = headers.indexOf('centroid_y')
def ct_idx     = headers.indexOf('cell_type')
def tissue_idx = headers.indexOf('tissue_id')
def group_idx  = headers.indexOf('experiment_group')
def pm_idx     = headers.indexOf('positive_markers')
def cp_idx     = headers.indexOf('candidate_pattern')
def area_idx   = headers.indexOf('area')

println "Headers found : ${headers}"
println "Data rows     : ${dataLines.size()}"
if (unassignedOnly) println "Filter        : Unassigned cells only"

// ============================================================
// DISCOVER DISTINCT CELL TYPES (sorted, deterministic), ASSIGN COLORS
// ============================================================
def distinctTypes = dataLines.collect { line ->
    def cols = line.split('\t', -1)
    (ct_idx >= 0 && cols.size() > ct_idx && !cols[ct_idx].trim().isEmpty()) ?
        cols[ct_idx].trim() : "Unknown"
}.unique().sort()

def typeColors = [:]
def paletteIdx = 0
distinctTypes.each { ct ->
    if (ct == "Unassigned") {
        typeColors[ct] = UNASSIGNED_COLOR
    } else {
        typeColors[ct] = PALETTE[paletteIdx % PALETTE.size()]
        paletteIdx++
    }
}

println "Cell types found : ${distinctTypes}"

typeColors.each { typeName, color ->
    def pc = PathClass.fromString(typeName)
    if (pc != null) pc.setColor(color)
}

// ============================================================
// CREATE DETECTIONS
// ============================================================
def plane      = ImagePlane.getDefaultPlane()
def detections = []
def skipped    = 0
def filtered   = 0

dataLines.eachWithIndex { line, rowIdx ->
    def cols = line.split('\t', -1)

    try {
        String cellType = (ct_idx >= 0 && cols.size() > ct_idx && !cols[ct_idx].trim().isEmpty()) ?
                          cols[ct_idx].trim() : "Unknown"

        if (unassignedOnly && cellType != "Unassigned") {
            filtered++
            return
        }

        double globalX = Double.parseDouble(cols[cx_idx])
        double globalY = Double.parseDouble(cols[cy_idx])

        double radius = pointRadius
        if (area_idx >= 0 && cols.size() > area_idx && !cols[area_idx].trim().isEmpty()) {
            try {
                double area = Double.parseDouble(cols[area_idx])
                radius = Math.max(Math.sqrt(area / Math.PI), 3.0)
            } catch (NumberFormatException ignored) {}
        }

        String cellId = (cid_idx >= 0 && cols.size() > cid_idx) ? cols[cid_idx].trim() : ""

        def roi = ROIs.createEllipseROI(
            globalX - radius, globalY - radius, radius * 2, radius * 2, plane
        )

        def pathClass = PathClass.fromString(cellType)
        def detection = PathObjects.createDetectionObject(roi, pathClass)

        if (cellId) detection.setName(cellId)

        // ── String metadata (MeasurementList is numeric-only) ──
        detection.storeMetadataValue("cell_type", cellType)
        if (tissue_idx >= 0 && cols.size() > tissue_idx && !cols[tissue_idx].trim().isEmpty())
            detection.storeMetadataValue("tissue_id", cols[tissue_idx].trim())
        if (group_idx >= 0 && cols.size() > group_idx && !cols[group_idx].trim().isEmpty())
            detection.storeMetadataValue("experiment_group", cols[group_idx].trim())
        if (pm_idx >= 0 && cols.size() > pm_idx && !cols[pm_idx].trim().isEmpty())
            detection.storeMetadataValue("positive_markers", cols[pm_idx].trim())
        if (cp_idx >= 0 && cols.size() > cp_idx && !cols[cp_idx].trim().isEmpty())
            detection.storeMetadataValue("candidate_pattern", cols[cp_idx].trim())

        // ── Numeric measurement -- area, where present ──
        if (area_idx >= 0 && cols.size() > area_idx && !cols[area_idx].trim().isEmpty()) {
            try {
                def ml = detection.getMeasurementList()
                ml.put("area", Double.parseDouble(cols[area_idx].trim()))
                ml.close()
            } catch (NumberFormatException ignored) {}
        }

        detections.add(detection)

    } catch (Exception e) {
        skipped++
        if (skipped <= 10)
            println "  ⚠️  Row ${rowIdx + 2} skipped: ${e.message}"
    }
}

// ============================================================
// ADD TO QUPATH HIERARCHY & REFRESH
// ============================================================
def hierarchy = getCurrentImageData().getHierarchy()
hierarchy.addPathObjects(detections)
fireHierarchyUpdate()

println ""
println "✓ Imported : ${detections.size()} cells"
if (unassignedOnly) println "  (filtered : ${filtered} non-Unassigned rows skipped by unassignedOnly)"
println "✗ Skipped  : ${skipped} rows (parse errors)"
println ""

def typeCounts = [:]
detections.each { det ->
    def t = det.getPathClass()?.getName() ?: "Unclassified"
    typeCounts[t] = (typeCounts[t] ?: 0) + 1
}

println "Cell type breakdown:"
typeCounts.sort { -it.value }.each { t, cnt ->
    println String.format("  %-30s : %6d  (%4.1f%%)", t, cnt,
                          cnt * 100.0 / detections.size())
}

def withCandidate = detections.count { it.getMetadataString("candidate_pattern") }
if (withCandidate > 0) {
    println ""
    println "${withCandidate} Unassigned cell(s) carry a candidate_pattern suggestion -- " +
            "click one and check its metadata panel."
}
