/*
===============================================================================
SPATIA Pipeline - Triad Visualization Script
File: 07-2_triad_visualization.groovy
===============================================================================

STATUS
------
Written but NOT executed against a real QuPath project — this sandbox has no
QuPath installation to run it in. Modeled directly on the same import/render
pattern already used in 05-4-2_cell-typing_visualization.groovy (ellipse
detections at centroid, PathClass + color per category, TSV columns attached
as measurements/metadata). The one new API used here — storeMetadataValue()
for string fields — was verified to exist against QuPath's own public javadoc
(confidence: high that the method exists; medium on real-world behavior at
scale — QuPath's own docs specifically caution that storing metadata on many
detection objects can raise memory use, and one image's worth of triads here
means 3 detections per triad, so a few hundred triads is a few hundred to a
few thousand detections). Spot-check the first real run's rendered triads
against 07-1's own printed triad count before trusting the QuPath view.

-------------------------------------------------------------------------------

MAINTENANCE NOTE (developer-facing — not needed to run this script)
---------------------------------------------------------------------
This file exists identically in both:
  pipeline with semi-automatic cell typing/07-2_triad_visualization.groovy
  pipieline with automatic cell typing/07-2_triad_visualization.groovy
Neither folder is git-tracked, so nothing enforces the two copies staying in
sync — edit both if you change this script. Mirrors the same intentional
two-folder duplication already established for
00_ROI_extract_mask_project.groovy.

-------------------------------------------------------------------------------

OVERVIEW
--------
Imports the *_triads.tsv file produced by 07-1_triad_visualization_tsv.ipynb
(or its automatic-typing counterpart, 07-1_a) and renders each triad member
as a colored ellipse detection object at its centroid, directly in the open
QuPath project — so you can visually cross-check whether the triads
triads.py detected make biological sense on the real tissue image, not just
in its numeric CSV output.

Each row (one cell, in one role, in one triad) is rendered:
  • At its centroid location (global pixel coordinates, used directly)
  • Colored by role — gold = anchor, blue = partner1, red = partner2,
    matching the exact colors triads.py's plot_triad_qc() already uses for
    its own QC plots, so the Python plot and the QuPath view read the same
    way
  • Named after its triad_id (visible in QuPath's object list and
    searchable), so you can find all 3 cells belonging to one specific
    triad in one place
  • Tagged with cell_type, experiment_group, role, and cell_id as QuPath
    metadata (string key/value pairs — QuPath's numeric MeasurementList
    can't hold text, so these use storeMetadataValue() instead, see STATUS)
  • Tagged with the 3 pairwise distances (dist_anchor_p1_um,
    dist_anchor_p2_um, dist_p1_p2_um) as numeric measurements, wherever that
    role's row has a value (07-1 intentionally leaves some of these blank
    per role — see its own docs)

-------------------------------------------------------------------------------

USER CONFIGURATION PARAMETERS
-----------------------------

tsvPath (String)
  → Full path to the *_triads.tsv file generated by 07-1 (or 07-1_a)

pointRadius (double)
  → Radius in pixels for each rendered ellipse. No cell-area info is
    available from triad_pairs.csv (unlike 05-4-2's cell-typing TSV, which
    has one). Default: 6.0 — a bit larger than 05-4-2's no-area fallback
    (5.0) so triad markers stay visually distinct if both layers are open
    at once.

-------------------------------------------------------------------------------

ROLE COLOR MAP
---------------
The 3 canonical roles 07-1 currently writes (DC_anchor / CD4_partner /
CD8_partner) get fixed colors matching plot_triad_qc():

  role containing "anchor"              → Gold  (255, 215, 0)
  role containing "partner1", or the    → Blue  (31, 119, 180)
    first distinct "partner"-ish role seen
  role containing "partner2", or the    → Red   (214, 39, 40)
    second distinct "partner"-ish role seen

Matching is substring/order-based, not a hardcoded exact-string list — if
you ever rename 07-1's role labels (e.g. for a different anchor/partner
triad than DC-CD4-CD8), this script still assigns a sensible color instead
of erroring or defaulting everything to grey. Any unexpected 4th+ distinct
role value falls back to a small rotating palette (green, purple, orange).

-------------------------------------------------------------------------------

WORKFLOW
--------

Step 1: Set tsvPath (and optionally pointRadius)
Step 2: Read TSV headers, validate required columns
Step 3: Scan all rows once to discover distinct `role` values, assign colors
Step 4: Register a PathClass + color per distinct role
Step 5: For each row: create an ellipse ROI at (centroid_x, centroid_y),
        assign PathClass = role, set object name = triad_id, store
        cell_type/experiment_group/role/cell_id as metadata, store the 3
        distance columns as numeric measurements wherever non-empty
Step 6: Add all detections to the hierarchy, refresh, print a role-count
        breakdown (mirrors 05-4-2's cell-type breakdown)

-------------------------------------------------------------------------------

REQUIRED TSV COLUMNS
---------------------
triad_id, role, cell_type, centroid_x, centroid_y

OPTIONAL TSV COLUMNS
---------------------
experiment_group, cell_id, dist_anchor_p1_um, dist_anchor_p2_um,
dist_p1_p2_um (each may be blank on a given row by design — see 07-1's own
docs for which distance fields are left empty per role)

-------------------------------------------------------------------------------

COORDINATE HANDLING
---------------------
centroid_x / centroid_y in the TSV are already global pixel coordinates,
carried through unchanged from triads.py's own centroid_x/centroid_y via
find_triads() -> *_triad_pairs.csv -> 07-1's TSV export — used directly for
ROI placement, no offset math needed. (Unlike 05-4-2, which handles cropped-
tile offsets: triad detection runs on whole-image matched-cell data, not
tiles, so that concern doesn't apply here.)

-------------------------------------------------------------------------------

MEASUREMENTS / METADATA ATTACHED
----------------------------------
Numeric (MeasurementList):
  dist_anchor_p1_um, dist_anchor_p2_um, dist_p1_p2_um  (only where non-empty)

String (metadata, via storeMetadataValue — a new pattern for this repo's
QuPath scripts; see STATUS above for why):
  role, cell_type, experiment_group, cell_id

Object name (visible in QuPath's annotation/detection list, searchable):
  triad_id

-------------------------------------------------------------------------------

CONSOLE OUTPUT EXAMPLE
-------------------------
Headers found : [triad_id, role, cell_type, centroid_x, centroid_y, experiment_group, cell_id, dist_anchor_p1_um, dist_anchor_p2_um, dist_p1_p2_um]
Data rows     : 369

✓ Imported : 369 triad-member cells (123 triads)
✗ Skipped  : 0 rows (parse errors)

Role breakdown:
  DC_anchor      :    123  (33.3%)
  CD4_partner    :    123  (33.3%)
  CD8_partner    :    123  (33.3%)

-------------------------------------------------------------------------------

ERROR HANDLING
-----------------
TSV empty or invalid       → Script exits with error
Missing required columns   → Lists missing fields and exits
Row parse failure          → Skipped (first 10 warnings printed)
Missing role                → Defaults to "Unknown" (grey)

-------------------------------------------------------------------------------

PREREQUISITES
----------------
• QuPath with Groovy scripting support
• TSV generated from: export_triads_for_qupath.py (canonical, deterministic
  CLI script — see docs/export_triads_for_qupath.md). The older notebooks
  07-1_triad_visualization_tsv.ipynb / 07-1_a still produce a compatible TSV
  (role values differ cosmetically — "DC_anchor" vs "anchor" etc. — this
  script's role-color matching handles both) but are no longer the
  recommended path.
• Run via: QuPath -> Automate -> Script Editor -> paste -> Run
  (interactive only — no headless/CLI mode, same limitation as
  00_ROI_extract_mask_project.groovy and 05-4-2)

-------------------------------------------------------------------------------

RELATED SCRIPTS
-------------------
spatia/analysis/triads.py (find_triads / run_triad_analysis)
  -> Detects triads, writes *_triad_pairs.csv

export_triads_for_qupath.py (canonical) / 07-1_triad_visualization_tsv.ipynb
/ 07-1_a (legacy, still compatible)
  -> Converts *_triad_pairs.csv -> *_triads.tsv (this script's input)

07-2_triad_visualization.groovy
  -> This script -> renders triads in QuPath

===============================================================================
*/
import qupath.lib.objects.PathObjects
import qupath.lib.roi.ROIs
import qupath.lib.regions.ImagePlane
import qupath.lib.objects.classes.PathClass

// ============================================================
// ⚠️  USER CONFIGURATION — CHANGE THIS PATH
// ============================================================
def tsvPath     = "/path/to/triad_qupath_exports/IMAGE_ID_triads.tsv"
def pointRadius = 6.0

// ============================================================
// FIXED COLORS — match plot_triad_qc()'s ANCHOR/PARTNER1/PARTNER2 scheme
// ============================================================
def ANCHOR_COLOR     = getColorRGB(255, 215, 0)    // gold
def PARTNER1_COLOR   = getColorRGB(31,  119, 180)  // blue
def PARTNER2_COLOR   = getColorRGB(214, 39,  40)   // red
def UNKNOWN_COLOR    = getColorRGB(100, 100, 100)  // grey
def FALLBACK_PALETTE = [
    getColorRGB(76,  175, 80),   // green
    getColorRGB(156, 39,  176),  // purple
    getColorRGB(255, 152, 0),    // orange
]

// ============================================================
// READ TSV
// ============================================================
def allLines = new File(tsvPath).readLines()
if (allLines.size() < 2) {
    println "ERROR: TSV file is empty or has no data rows: ${tsvPath}"
    return
}

def headers   = allLines[0].split('\t').toList()
def dataLines = allLines[1..-1]

def requiredCols = ['triad_id', 'role', 'cell_type', 'centroid_x', 'centroid_y']
def missingCols = requiredCols.findAll { headers.indexOf(it) < 0 }
if (missingCols) {
    println "ERROR: Missing required columns: ${missingCols}"
    println "Available headers: ${headers}"
    return
}

def tid_idx   = headers.indexOf('triad_id')
def role_idx  = headers.indexOf('role')
def ct_idx    = headers.indexOf('cell_type')
def cx_idx    = headers.indexOf('centroid_x')
def cy_idx    = headers.indexOf('centroid_y')
def group_idx = headers.indexOf('experiment_group')
def cid_idx   = headers.indexOf('cell_id')
def dap1_idx  = headers.indexOf('dist_anchor_p1_um')
def dap2_idx  = headers.indexOf('dist_anchor_p2_um')
def dp1p2_idx = headers.indexOf('dist_p1_p2_um')

println "Headers found : ${headers}"
println "Data rows     : ${dataLines.size()}"

// ============================================================
// DISCOVER DISTINCT ROLES, ASSIGN COLORS
// (substring/order match, not a hardcoded exact-string list — see header)
// ============================================================
def distinctRoles = dataLines.collect { line ->
    def cols = line.split('\t', -1)
    (role_idx >= 0 && cols.size() > role_idx && !cols[role_idx].trim().isEmpty()) ?
        cols[role_idx].trim() : "Unknown"
}.unique()

def roleColors  = [:]
def partnerSeen = 0
def fallbackIdx = 0
distinctRoles.each { role ->
    def lower = role.toLowerCase()
    if (role == "Unknown") {
        roleColors[role] = UNKNOWN_COLOR
    } else if (lower.contains("anchor")) {
        roleColors[role] = ANCHOR_COLOR
    } else if (lower.contains("partner1") || (lower.contains("partner") && partnerSeen == 0)) {
        roleColors[role] = PARTNER1_COLOR
        partnerSeen++
    } else if (lower.contains("partner2") || (lower.contains("partner") && partnerSeen == 1)) {
        roleColors[role] = PARTNER2_COLOR
        partnerSeen++
    } else {
        roleColors[role] = FALLBACK_PALETTE[fallbackIdx % FALLBACK_PALETTE.size()]
        fallbackIdx++
    }
}

println "Roles found   : ${distinctRoles}"

// Register a PathClass + color per role
roleColors.each { roleName, color ->
    def pc = PathClass.fromString(roleName)
    if (pc != null) pc.setColor(color)
}

// ============================================================
// CREATE DETECTIONS
// ============================================================
def plane      = ImagePlane.getDefaultPlane()
def detections = []
def skipped    = 0

dataLines.eachWithIndex { line, rowIdx ->
    def cols = line.split('\t', -1)

    try {
        double globalX = Double.parseDouble(cols[cx_idx])
        double globalY = Double.parseDouble(cols[cy_idx])

        String role = (role_idx >= 0 && cols.size() > role_idx && !cols[role_idx].trim().isEmpty()) ?
                      cols[role_idx].trim() : "Unknown"
        String cellType = (ct_idx >= 0 && cols.size() > ct_idx && !cols[ct_idx].trim().isEmpty()) ?
                          cols[ct_idx].trim() : "Unknown"
        String triadId = (tid_idx >= 0 && cols.size() > tid_idx) ? cols[tid_idx].trim() : ""

        def roi = ROIs.createEllipseROI(
            globalX - pointRadius,
            globalY - pointRadius,
            pointRadius * 2,
            pointRadius * 2,
            plane
        )

        def pathClass = PathClass.fromString(role)
        def detection = PathObjects.createDetectionObject(roi, pathClass)

        if (triadId) detection.setName(triadId)

        // ── String metadata (MeasurementList is numeric-only, see STATUS) ──
        detection.storeMetadataValue("role", role)
        detection.storeMetadataValue("cell_type", cellType)
        if (group_idx >= 0 && cols.size() > group_idx && !cols[group_idx].trim().isEmpty())
            detection.storeMetadataValue("experiment_group", cols[group_idx].trim())
        if (cid_idx >= 0 && cols.size() > cid_idx && !cols[cid_idx].trim().isEmpty())
            detection.storeMetadataValue("cell_id", cols[cid_idx].trim())

        // ── Numeric measurements — only the 3 distance columns, where present ──
        def ml = detection.getMeasurementList()
        [[dap1_idx, "dist_anchor_p1_um"], [dap2_idx, "dist_anchor_p2_um"], [dp1p2_idx, "dist_p1_p2_um"]].each { pair ->
            def idx = pair[0]
            def name = pair[1]
            if (idx >= 0 && cols.size() > idx && !cols[idx].trim().isEmpty()) {
                try {
                    ml.put(name, Double.parseDouble(cols[idx].trim()))
                } catch (NumberFormatException ignored) {}
            }
        }
        ml.close()

        detections.add(detection)

    } catch (Exception e) {
        skipped++
        if (skipped <= 10)
            println "  ⚠️  Row ${rowIdx + 2} skipped: ${e.message}"
    }
}

// ============================================================
// ADD TO QUPATH HIERARCHY & REFRESH
// ============================================================
def hierarchy = getCurrentImageData().getHierarchy()
hierarchy.addPathObjects(detections)
fireHierarchyUpdate()

def nTriads = detections.collect { it.getName() }.findAll { it }.unique().size()

println ""
println "✓ Imported : ${detections.size()} triad-member cells (${nTriads} triads)"
println "✗ Skipped  : ${skipped} rows (parse errors)"
println ""

def roleCounts = [:]
detections.each { det ->
    def r = det.getPathClass()?.getName() ?: "Unclassified"
    roleCounts[r] = (roleCounts[r] ?: 0) + 1
}

println "Role breakdown:"
roleCounts.sort { -it.value }.each { r, cnt ->
    println String.format("  %-30s : %6d  (%4.1f%%)", r, cnt,
                          cnt * 100.0 / detections.size())
}
